from .base import BaseAlgorithm
from .svm import SimpleSVM
from .adaboost import AdaBoost
from .dbscan import DBSCAN
from .kmeans import KMeans
from .mlp import MLP
from .pca import PCA
from .id3 import ID3
from .linear_regression import LinearRegression
from .nb_number import NBNumber